version: '2.1'

volumes:
  db-backups:
  db-data:

services:
  db:
    image: kartoza/postgis:13.0
    volumes:
      - db-data:/var/lib/postgresql
    restart: on-failure
    healthcheck:
      test: "exit 0"

  dbbackups:
    image: kartoza/pg-backup:13.0
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG_gis
      - REMOVE_BEFORE=7 # Remove backups older than (in days)
      - POSTGRES_HOST=db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
      - CRON_SCHEDULE=*/5 * * * *
      # For restore script
      - TARGET_DB=gis
      - WITH_POSTGIS=1
      - TARGET_ARCHIVE=/backups/target_archive.dmp
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
